version: 2
updates:
  - package-ecosystem: "maven" # or "gradle"
    directory: "/SCA/java"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directories:
      - "/SCA/javascript"
    schedule:
      interval: "weekly"
      
  - package-ecosystem: "pip"
    directory: "/SCA/python/requirements.txt"
    schedule:
      interval: "weekly"

  - package-ecosystem: "bundler"
    directory: "/SCA/ruby"
    schedule:
      interval: "weekly"
