version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/sast/csharp"
    schedule:
      interval: "weekly"

  - package-ecosystem: "maven" # or "gradle"
    directory: "/SCA/java"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directories:
      - "/sast/javascript"
      - "/sast/typescript"
      - "/SCA/javascript"
    schedule:
      interval: "weekly"

  - package-ecosystem: "composer"
    directory: "/sast/php"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/sca/python"
    schedule:
      interval: "weekly"

  - package-ecosystem: "bundler"
    directory: "/sca/ruby"
    schedule:
      interval: "weekly"
